### ISSUE TITLE
How to grab images from https?

### ISSUE THREAD

**Issue by monecchi** [pongstr/pongstagr.am#20]
Hello. Sorry for posting an issue here, as I consider the following not an issue but rather a general question:

How to set up the plugin so that instagram screenshots are loaded over https instead over the http protocol? Any chances I can get it working this way. I'm running a server with SSL enabled.

Here's a test page: https://www.pizzariameurancho.com.br/pizzagram/

Thanks in advance.

**Comment by pongstr** [comment]
hmm.. by default, instagram loads all images via `https`, I suggest you run a test page that isn't on SSL and then see whether instagram content still loads via `http`, if it doesn't then I'm guessing its an issue on your setup.

Check out this [page](https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content) regarding mix content, you might also want to check whether `bootstrap.js` is loaded.
