### ISSUE TITLE
Stopped pulling data

### ISSUE THREAD

**Issue by ZxIRAX** [pongstr/pongstagr.am#21]
within the last week, the API appears to have stopped pulling data. in the console, it said it was related to bio.data. I have disabled this but no data is returned.

I have recently changed my password, do I need to create a new access token?

**Comment by ZxIRAX** [comment]
Ok, it's working. If you change your password, you need to generate a new access token. FYI - the link to generate an access ID and token no longer works.

**Comment by pongstr** [comment]
Yea, I think instagram asked jelled to not expose that for security reasons, however the process is still documented on his website though.
