### ISSUE TITLE
github page https mixed content issues

### ISSUE THREAD

**Issue by anselmh** [pongstr/pongstagr.am#22]
Due to the yml config that points the base url to http which is used for all assets the page loads improperly when accessing via https: https://pongstr.github.io/pongstagr.am/. This is due to mixed content blocking.

You can fix this by just using the HTTPS version in the config instead of HTTP.

**Comment by pongstr** [comment]
0a588f57cd834535a6a7ab8c16a5b995b05ae06e Thanks!
